export const listOfNotCalculate = [
  'Part',
  'Type',
  'Dimensions',
  'Battery Capacity',
  'Battery Life',
  'CPU Microarchitecture',
  'SSD Storage',
  'SSD Type',
  'Storage',
  'Front Facing Webcam',
  'Images',
  'Name',
  'GPU Memory',
  'Model',
  'Screen Surface Finish',
  'HDD Storage',
  'Rear Facing Webcam',
  '_id',
  'SellerName',
  'Seller',
  '0',
  'CPU Boost Clock',
  'CPU Core Clock',
];
